---
- name: Provision VM and deploy HYLASTIX stack
  hosts: web
  become: true

  vars:
    app_root: /opt/hylastix
    docker_project_name: hylastix

  roles:
    - role: docker
    - role: app_deploy
    - role: keycloak