---
- name: Provision VM and deploy stack
  hosts: web
  become: true

  vars:
    app_root: /opt/iac-demo
    docker_project_name: iac-demo

  roles:
    - role: docker
    - role: app_deploy
    - role: keycloak